init: false
settings:
  siteName: "Imageboard"
  reCaptcha: false
  reCaptchaPubKey: ""
  reCaptchaPrivKey: ""
  rules: ""
  videoThumbnails: false
  pdfThumbnails: false
  pdfView: false
  databaseURI: "file:db.sql"
  contentStorage: "file://$CWD/data/content/"
  cacheStorage: "file://$CWD/data/cache/"

