init: false
settings:
  siteName: "KittehBooru"
  reCaptcha: false
  reCaptchaPubKey: ""
  reCaptchaPrivKey: ""
  rules: ""
  videoThumbnails: false
  pdfThumbnails: false
  pdfView: false
  databaseURI: user=dbuser dbname=booru sslmode=disable
  databaseType: postgres
  contentStorage: file://data/content/
  thumbnailsStorage: file://data/cache/
  contentURL: /content/
  thumbnailURL: /thumbnail/
  listenAddress: 0.0.0.0:8000