init: false
settings:
  siteName: "Imageboard"
  reCaptcha: false
  reCaptchaPubKey: ""
  reCaptchaPrivKey: ""
  rules: ""
  videoThumbnails: false
  pdfThumbnails: false
  pdfView: false
  databaseURI: "file:db.sql"
  contentStorage: "file://$CWD/data/content/"
  thumbnailsStorage: "file://$CWD/data/cache/"
  #for S3
  #contentStorage: s3://kitcontent/content/
  #thumbnailsStorage: s3://kitcontent/cache/
  #contentURL: https://kitcontent.s3.amazonaws.com/content/
  #thumbnailURL: https://kitcontent.s3.amazonaws.com/cache/