init: false
settings:
  siteName: "Imageboard"
  reCaptcha: false
  reCaptchaPubKey: ""
  reCaptchaPrivKey: ""
  rules: ""
  videoThumbnails: false
  pdfThumbnails: false
  pdfView: false
  databaseURI: file:db.sql?_journal=WAL&cache=shared&_busy_timeout=5000
  contentStorage: file://data/content/
  thumbnailsStorage: file://data/cache/
  contentURL: /content/
  thumbnailURL: /thumbnail/